import 'dart:async';
import 'dart:io';

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:movieverse/core/network/http_overrides.dart';
import 'package:movieverse/core/theme/app_theme.dart';
import 'package:movieverse/core/utils/logger.dart';
import 'package:movieverse/presentation/screens/splash_screen.dart';

void main() async {
  // Bypass SSL certificate errors (for development/debugging)
  HttpOverrides.global = MyHttpOverrides();

  runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();

    // Set preferred orientations
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);

    // Set system UI overlay style
    SystemChrome.setSystemUIOverlayStyle(const SystemUiOverlayStyle(
      statusBarColor: Colors.transparent,
      statusBarIconBrightness: Brightness.light,
      statusBarBrightness: Brightness.dark,
    ));

    try {
      // Initialize Firebase
      // Note: Ensure google-services.json (Android) and GoogleService-Info.plist (iOS) are present
      // or use DefaultFirebaseOptions if generated by flutterfire configure.
      await Firebase.initializeApp();
      AppLogger.success('Main', 'Firebase Initialized Successfully');

      // Check Internet Connectivity
      try {
        final result = await InternetAddress.lookup('google.com');
        if (result.isNotEmpty && result[0].rawAddress.isNotEmpty) {
          AppLogger.success('Network', 'Internet Connection Available');
        }
      } catch (_) {
        AppLogger.error(
            'Network', 'No Internet Connection. Emulator may be offline.');
      }
    } catch (e) {
      AppLogger.error(
          'Main', 'Firebase initialization failed. Auth features may not work.',
          error: e);
      // Continue anyway to show the UI, though auth-dependent features will fail
    }

    runApp(const ProviderScope(child: MyApp()));
  }, (error, stack) {
    AppLogger.error('Main', 'Uncaught Error in root zone',
        error: error, stackTrace: stack);
    // Report to Crashlytics here in production
  });
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      title: 'Movieverse',
      debugShowCheckedModeBanner: false,
      theme: AppTheme.darkTheme,
      home: const SplashScreen(),
    );
  }
}
